#%RAML 1.0 Library
types:
  get_asset_response:
    description: retrieving by id
    type: array
    items:
      properties:
        name:
          description: name of the company
          type: string
          required: true
        price:
          description: amount of the product
          type: number
          required: false
        description:
          description: description
          type: string
          required: false
        status:
          description: status of the asset
          type: string
          required: false
        quantity:
          description: quantity of the product
          type: number
          required: false
        id:
          description: id
          type: string
          required: true 
        accountid:
          description: accountid
          type: string
          required: true
        